### ISSUE TITLE
v. 5.2.1 - Generic xxxx board name in GUI - Translate it

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#181] opened 2021-05-07 09:22 UTC
@benzino77

Currently the GUi is full translated execpe for

![image](https://user-images.githubusercontent.com/1262554/117428487-6bf88800-af26-11eb-8847-986cb1da32d2.png)

Generic ESP8266
Generic ESP32 

the other boards names are owned names and shouldn't translated.

But "Generic xxxx" is not translated.

To have a fully translated GUI I propose please to add only

- Generic ESP8266
- Generic ESP32

to the list of strings in language files.

Thanks. KR.

**Comment by benzino77** [comment] 2021-05-07 09:27
Closing as this is duplicate of #137.

**Closed by benzino77** 2021-05-07 09:27 UTC

**Comment by bovirus** [comment] 2021-05-07 09:31
@benzino77 

Sorry but don't close this request.
It's not a duplicate.

The other request was more complicated

Translate all name
Make the board list in alphabetical order

Instead this request is more simple

Just add two strings to the language files.
