### ISSUE TITLE
[.pioenvs/custom/src/tasmota.ino.cpp.o] Error 1

### ISSUE THREAD

**Issue by motorrad** [benzino77/tasmocompiler#63] opened 2020-05-10 05:00 UTC
Hi
got following Error:
In file included from /tmp/Tasmota/tasmota/tasmota.ino:43:0:
tasmota/i18n.h:626:37: fatal error: language/de-DE.h: No such file or directory
   #include INCLUDE_FILE(MY_LANGUAGE)
                                     ^
compilation terminated.
Compiling .pioenvs/custom/src/WiFiClientSecureLightBearSSL.cpp.o
Compiling .pioenvs/custom/src/Parsing.cpp.o
In file included from tasmota/my_user_config.h:731:0,
                 from tasmota/WiFiClientSecureLightBearSSL.cpp:23:
tasmota/user_config_override.h:4:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pioenvs/custom/lib5c2/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
*** [.pioenvs/custom/src/tasmota.ino.cpp.o] Error 1
Compiling .pioenvs/custom/lib5c2/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
========================= [FAILED] Took 47.46 seconds =========================
Finished. Exit code: 1.

**Comment by benzino77** [comment] 2020-05-10 10:18
Duplicate of #57

**Closed by benzino77** 2020-05-10 10:18 UTC

**Comment by benzino77** [comment] 2020-05-10 10:42
It should be addressed by benzino77/tasmocompiler@13d0713f85176e40d49df105d20dcc7d6642073d
